export const ADD_ASSISTANT_NAME = "ADD_ASSISTANT_NAME";
export const ADD_ASSISTANT_STYLE = "ADD_ASSISTANT_STYLE";
export const SIGNUP_USER = "SIGNUP_USER";
export const CREATE_ASSISTANT = "CREATE_ASSISTANT";
export const DELETE_ASSISTANT = "DELETE_ASSISTANT";
export const ADD_NEW_ASSISTANT = "ADD_NEW_ASSISTANT";
export const SET_USER = "SET_USER";
export const GET_ASSISTANTS = "GET_ASSISTANTS";
export const EDIT_ASSISTANT_LOCAL = "EDIT_ASSISTANT_LOCAL";
export const EDIT_ASSISTANT = "EDIT_ASSISTANT";
export const LOGOUT_USER = "LOGOUT_USER";

export const ERROR = "ERROR";
