export const ADD_ASSISTANT_NAME = "ADD_ASSISTANT_NAME";
export const ADD_ASSISTANT_STYLE = "ADD_ASSISTANT_STYLE";
export const SIGNUP_USER = "SIGNUP_USER";
export const CREATE_ASSISTANT = "CREATE_ASSISTANT";
export const DELETE_ASSISTANT = "DELETE_ASSISTANT";
export const ADD_NEW_ASSISTANT = "ADD_NEW_ASSISTANT";
export const SET_USER = "SET_USER";

export const ERROR = "ERROR";
